# Generated by Django 2.2.1 on 2019-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('G', '汽油'), ('O', '油')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='product_category',
            field=models.CharField(choices=[('G', '汽油'), ('O', '油')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('L', '装货地'), ('U', '卸货地'), ('Q', '质检点'), ('O', '合作油站'), ('B', '黑点')], max_length=1),
        ),
    ]
