# Generated by Django 2.2.1 on 2019-06-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_type', '-updated']},
        ),
    ]
