# Generated by Django 2.2.1 on 2019-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingstation',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='oilstation',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='qualitystation',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='unloadingstation',
            name='centroid',
        ),
        migrations.AddField(
            model_name='loadingstation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingstation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilstation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilstation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitystation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitystation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unloadingstation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unloadingstation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadingstation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loadingstation',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oilstation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oilstation',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualitystation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualitystation',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unloadingstation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unloadingstation',
            name='radius',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
