# Generated by Django 2.2.1 on 2019-11-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='driver_work_license_expires_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='driver_work_license_expires_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
    ]
