# Generated by Django 2.2.1 on 2019-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_measure_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
