# Generated by Django 2.2.1 on 2019-07-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.CustomerProfile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='station',
            name='clients',
        ),
    ]
