# Generated by Django 2.2.1 on 2019-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('L', '装货地'), ('U', '卸货地'), ('Q', '质检点'), ('G', '下车地管理'), ('O', '合作油站'), ('B', '黑点'), ('P', '合法停车区域'), ('R', '供应商'), ('C', '自定义')], max_length=1),
        ),
    ]
