# Generated by Django 2.2.1 on 2019-10-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsetting',
            name='driver_license_duration',
        ),
        migrations.RemoveField(
            model_name='basicsetting',
            name='vehicle_insurance_duration',
        ),
        migrations.RemoveField(
            model_name='basicsetting',
            name='vehicle_operation_duration',
        ),
        migrations.RemoveField(
            model_name='basicsetting',
            name='vehicle_review_duration',
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='driver_license_expires_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='driver_license_expires_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='trailer_usage_expires_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='trailer_usage_expires_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_insurance_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_insurance_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_license_expires_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_license_expires_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_operation_permit_notification_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='vehicle_operation_permit_notification_duration_unit',
            field=models.CharField(choices=[('D', '日'), ('M', '月')], default='D', max_length=1),
        ),
    ]
