# Generated by Django 2.2.1 on 2019-06-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190606_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='price_vary_duration',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
