# Generated by Django 2.2.1 on 2019-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190506_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingstation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oilstation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitystation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unloadingstation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
