# Generated by Django 2.2.1 on 2019-09-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190902_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
