# Generated by Django 2.2.1 on 2019-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190926_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.FloatField(default=0)),
                ('rapid_acceleration', models.PositiveIntegerField(default=0)),
                ('rapid_deceleration', models.PositiveIntegerField(default=0)),
                ('sharp_turn', models.PositiveIntegerField(default=0)),
                ('over_speed', models.PositiveIntegerField(default=0)),
                ('over_speed_duration', models.PositiveIntegerField(default=0)),
                ('rotation_speed', models.PositiveIntegerField(default=0)),
                ('vehicle_review_duration', models.PositiveIntegerField(default=0)),
                ('driver_license_duration', models.PositiveIntegerField(default=0)),
                ('vehicle_operation_duration', models.PositiveIntegerField(default=0)),
                ('vehicle_insurance_duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AlarmSetting',
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('L', '装货地'), ('U', '卸货地'), ('Q', '质检点'), ('G', '下车地管理'), ('O', '合作油站'), ('B', '黑点'), ('P', '合法停车区域'), ('R', '供应商'), ('C', 'Custom')], max_length=1),
        ),
    ]
