# Generated by Django 2.2.1 on 2019-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('info', '0002_auto_20190801_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='customer',
        ),
        migrations.AddField(
            model_name='station',
            name='customers',
            field=models.ManyToManyField(to='hr.CustomerProfile'),
        ),
    ]
