# Generated by Django 2.2.1 on 2019-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_othercosttype_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
