# Generated by Django 2.2.1 on 2019-07-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190711_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.CustomerProfile'),
        ),
    ]
