# Generated by Django 2.2.1 on 2019-06-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190606_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('L', 'Litre'), ('T', 'T')], default='T', max_length=1),
        ),
    ]
