# Generated by Django 2.2.1 on 2019-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190728_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rapid_acceleration', models.PositiveIntegerField(default=0)),
                ('rapid_deceleration', models.PositiveIntegerField(default=0)),
                ('sharp_turn', models.PositiveIntegerField(default=0)),
                ('over_speed', models.PositiveIntegerField(default=0)),
                ('over_speed_duration', models.PositiveIntegerField(default=0)),
                ('rotation_speed', models.PositiveIntegerField(default=0)),
                ('vehicle_review_duration', models.PositiveIntegerField(default=0)),
                ('driver_license_duration', models.PositiveIntegerField(default=0)),
                ('vehicle_operation_duration', models.PositiveIntegerField(default=0)),
                ('vehicle_insurance_duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
