# Generated by Django 2.2.1 on 2020-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20191127_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='station',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
