# Generated by Django 2.2.1 on 2019-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_station_price_vary_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='price_vary_duration_unit',
            field=models.CharField(choices=[('周', '周'), ('月', '月'), ('年', '年')], default='月', max_length=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='price_vary_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
