# Generated by Django 2.2.1 on 2019-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190606_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='price_vary_duration_unit',
            field=models.CharField(choices=[('W', '周'), ('M', '月'), ('Y', '年')], default='M', max_length=1),
        ),
    ]
