# Generated by Django 2.2.1 on 2019-07-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alarmsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('distance', models.FloatField(default=0)),
                ('average_time', models.FloatField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_points', to='info.Station')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_points', to='info.Station')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
