# Generated by Django 2.2.1 on 2019-08-12 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190807_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('L', '装货地'), ('U', '卸货地'), ('Q', '质检点'), ('O', '合作油站'), ('B', '黑点'), ('P', '合法停车区域'), ('R', '供应商'), ('C', 'Custom')], max_length=1),
        ),
    ]
