# Generated by Django 2.2.1 on 2019-06-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190607_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='unit_weight',
        ),
    ]
