# Generated by Django 2.2.1 on 2019-08-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190813_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
