# Generated by Django 2.2.1 on 2019-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190607_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('L', '公升'), ('T', '吨')], default='T', max_length=1),
        ),
    ]
