# Generated by Django 2.2.1 on 2019-06-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190606_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated']},
        ),
    ]
