# Generated by Django 2.2.1 on 2019-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190821_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='customers',
            field=models.ManyToManyField(to='hr.CustomerProfile'),
        ),
    ]
