# Generated by Django 2.2.1 on 2019-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_staffprofile_status'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypolicy',
            name='policy_type',
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='departments',
            field=models.ManyToManyField(to='hr.Department'),
        ),
    ]
