# Generated by Django 2.2.1 on 2019-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypolicy',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='policy_type',
            field=models.CharField(choices=[('S', '壳牌'), ('T', '危化品运输部'), ('O', '油品'), ('A', '全部')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='SecurityKnowledge',
        ),
    ]
