# Generated by Django 2.2.1 on 2019-10-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicyread',
            name='recent_read_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companypolicyread',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='security.CompanyPolicy'),
        ),
    ]
