# Generated by Django 2.2.1 on 2019-10-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_securityofficerprofile'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheckPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('check_address', models.CharField(blank=True, max_length=100, null=True)),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
                ('check_content', models.TextField()),
                ('check_result', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department')),
                ('security_officers', models.ManyToManyField(to='hr.SecurityOfficerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
