# Generated by Django 2.2.1 on 2019-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(choices=[(0, '判断题'), (1, '单选题'), (2, '多选题')], default=0),
        ),
    ]
