# Generated by Django 2.2.1 on 2019-08-29 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190829_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionresult',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
