# Generated by Django 2.2.1 on 2019-11-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20191120_2133'),
        ('security', '0002_auto_20191120_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylearningprogram',
            name='audiences',
        ),
        migrations.AddField(
            model_name='securitylearningprogram',
            name='departments',
            field=models.ManyToManyField(to='hr.Department'),
        ),
    ]
