# Generated by Django 2.2.1 on 2019-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securitycheckplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycheckplan',
            name='check_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
