# Generated by Django 2.2.1 on 2019-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20190829_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='full_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
