# Generated by Django 2.2.1 on 2019-12-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0011_auto_20191127_1447'),
        ('hr', '0002_auto_20191120_2133'),
        ('security', '0004_auto_20191123_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('issue_type', models.PositiveIntegerField(choices=[(0, '车辆保养'), (1, '换季保养'), (2, '主车保轮'), (3, '挂车保轮'), (4, '车辆电器路维修'), (5, '轮胎维修'), (6, '轮胎更换'), (7, '附属设备维修'), (8, '中集设备维修'), (9, '车辆救援费用'), (10, '车辆物品配备车辆保养'), (11, '换季保养'), (12, '主车保轮'), (13, '挂车保轮'), (14, '车辆电器路维修'), (15, '轮胎维修'), (16, '轮胎更换'), (17, '附属设备维修'), (18, '中集设备维修'), (19, '车辆救援费用'), (20, '车辆物品配备')], default=0)),
                ('check_content', models.TextField(blank=True, null=True)),
                ('check_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityIssueRectifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rectifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SecurityIssue')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityIssueCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SecurityIssue')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityIssueAcceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SecurityIssue')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='securityissue',
            name='acceptors',
            field=models.ManyToManyField(related_name='security_issues_as_acceptors', through='security.SecurityIssueAcceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='ccs',
            field=models.ManyToManyField(related_name='security_issues_as_ccs', through='security.SecurityIssueCC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.SecurityOfficerProfile'),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='rectifiers',
            field=models.ManyToManyField(related_name='security_issues_as_rectifier', through='security.SecurityIssueRectifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityissue',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.Vehicle'),
        ),
    ]
