# Generated by Django 2.2.1 on 2019-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20191207_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityissue',
            name='issue_status',
            field=models.PositiveIntegerField(choices=[(1, '等待修理'), (2, '等待验收'), (3, '完毕')], default=1),
        ),
    ]
