# Generated by Django 2.2.1 on 2019-08-30 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_securitylearningprogram_securitylibrary_securitylibraryattachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLibraryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='security.SecurityLibrary')),
            ],
        ),
        migrations.AlterModelOptions(
            name='securitylearningprogram',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='securitylearningprogram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitylearningprogram',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='SecurityLibraryAttachments',
        ),
    ]
