# Generated by Django 2.2.1 on 2019-12-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_securityissue_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityissue',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
