# Generated by Django 2.2.1 on 2019-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_auto_20191207_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityissueacceptor',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityissuecc',
            name='cc_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityissuerectifier',
            name='rectified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
