# Generated by Django 2.2 on 2019-05-01 13:10

from django.db import migrations, models
import tms.core.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[tms.core.validations.validate_phone_number])),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), ('D', 'Driver'), ('E', 'Escort'), ('C', 'Customer')], default='S', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
