# Generated by Django 2.2.1 on 2019-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', '管理人员'), ('S', '工作人员'), ('D', '驾驶人员'), ('E', '押运人员'), ('C', '客户')], default='S', max_length=1),
        ),
    ]
