# Generated by Django 2.2.1 on 2019-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
