# Generated by Django 2.2.1 on 2019-07-03 15:16

from django.db import migrations, models
import tms.core.validations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[tms.core.validations.validate_username]),
        ),
    ]
