# Generated by Django 2.2.1 on 2019-05-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.StaffProfile'),
        ),
    ]
