# Generated by Django 2.2.1 on 2019-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191023_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', '管理人员'), ('S', '工作人员'), ('D', '驾驶人员'), ('E', '押运人员'), ('P', '外驾驶人员'), ('G', '外押运人员'), ('C', '客户'), ('T', '检查')], default='S', max_length=1),
        ),
    ]
