# Generated by Django 2.2.1 on 2019-05-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190508_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='parent_mobile',
            new_name='parent_number',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='spouse_mobile',
            new_name='spouse_number',
        ),
    ]
