# Generated by Django 2.2.1 on 2019-05-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_companystaffprofile_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='association',
            new_name='associated',
        ),
    ]
