# Generated by Django 2.2.1 on 2019-08-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190813_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
    ]
