# Generated by Django 2.2.1 on 2019-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_permission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
