# Generated by Django 2.2.1 on 2019-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191027_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permission',
            name='page',
            field=models.CharField(max_length=100),
        ),
    ]
