# Generated by Django 2.2.1 on 2019-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190814_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='actions',
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
