# Generated by Django 2.2.1 on 2019-05-27 13:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('road', '0001_initial'),
        ('account', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('N', 'Not Started'), ('P', 'Started'), ('C', 'Complete')], default='N', max_length=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('departure_time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_weight', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.DriverProfile')),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.EscortProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('loading_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('unloading_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderProductDeliver')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='missions',
            field=models.ManyToManyField(through='job.Mission', to='order.OrderProductDeliver'),
        ),
        migrations.AddField(
            model_name='job',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road.Route'),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
    ]
