# Generated by Django 2.2.1 on 2019-06-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobBillDocument',
        ),
    ]
