# Generated by Django 2.2.1 on 2019-05-29 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('O', 'Bill from Oil Station'), ('L', 'Bill from Loading Station'), ('U', 'Bill from UnLoading Station'), ('Q', 'Bill from Quality Station')], default='L', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
            ],
        ),
    ]
