# Generated by Django 2.2.1 on 2019-06-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverchangerequest',
            name='new_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escortchangerequest',
            name='new_escort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='escort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_escort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingrequest',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingrequest',
            name='escort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests_as_escort', to=settings.AUTH_USER_MODEL),
        ),
    ]
