# Generated by Django 2.2.1 on 2019-05-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='loading_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='unloading_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
