# Generated by Django 2.2.1 on 2019-05-24 14:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='arrived_at_loading_station',
        ),
        migrations.RemoveField(
            model_name='job',
            name='arrived_at_quality_station',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='arrived_at_unloading_station',
        ),
        migrations.AddField(
            model_name='job',
            name='arrived_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='departure_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road.Path'),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('N', 'Not Started'), ('P', 'Started'), ('C', 'Complete')], default='N', max_length=2),
        ),
    ]
