# Generated by Django 2.2.1 on 2019-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='step',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
