# Generated by Django 2.2.1 on 2019-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
