# Generated by Django 2.2.1 on 2019-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
