# Generated by Django 2.2.1 on 2019-06-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('start_due_time',)},
        ),
    ]
