# Generated by Django 2.2.1 on 2019-05-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_billdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillDocument',
            new_name='JobBillDocument',
        ),
    ]
