# Generated by Django 2.2.1 on 2019-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190524_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
