# Generated by Django 2.2.1 on 2019-06-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobreport',
            options={'ordering': ('month',)},
        ),
    ]
