# Generated by Django 2.2.1 on 2019-05-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_mission_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='path',
        ),
    ]
