# Generated by Django 2.2.1 on 2019-05-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190529_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbilldocument',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='job.Job'),
        ),
    ]
