# Generated by Django 2.2.1 on 2019-05-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190509_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.OrderProductDeliver'),
            preserve_default=False,
        ),
    ]
