# Generated by Django 2.2.1 on 2019-06-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190612_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverNotification',
        ),
    ]
