# Generated by Django 2.2.1 on 2019-06-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190617_1506'),
        ('account', '0001_initial'),
        ('job', '0004_driverchangerequest_escortchangerequest_otherparkingplacerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to='account.DriverProfile')),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to='account.EscortProfile')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_requests', to='vehicle.Vehicle')),
            ],
            options={
                'ordering': ['approved', '-approved_time', '-request_time'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='escortchangerequest',
            name='job',
        ),
        migrations.DeleteModel(
            name='OtherParkingPlaceRequest',
        ),
    ]
