# Generated by Django 2.2.1 on 2019-06-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_drivernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbilldocument',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobbilldocument',
            name='category',
            field=models.CharField(choices=[('O', 'Bill from Oil Station'), ('L', 'Bill from Loading Station'), ('U', 'Bill from UnLoading Station'), ('Q', 'Bill from Quality Station'), ('T', 'Bill from traffic')], default='L', max_length=1),
        ),
    ]
