# Generated by Django 2.2.1 on 2019-06-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('job', '0005_auto_20190617_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortchangerequest',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='driverchangerequest',
            unique_together={('job', 'new_driver')},
        ),
        migrations.AlterUniqueTogether(
            name='escortchangerequest',
            unique_together={('job', 'new_escort')},
        ),
    ]
