# Generated by Django 2.2.1 on 2019-05-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_weight',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
