# Generated by Django 2.2.1 on 2019-05-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
