# Generated by Django 2.2.1 on 2019-05-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=100)),
                ('rest_place', models.CharField(max_length=100)),
                ('change_place', models.CharField(max_length=100)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loading_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.LoadingStation')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.PositiveIntegerField()),
                ('weight_unit', models.CharField(choices=[('T', 't'), ('K', 'Kg')], default='T', max_length=2)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('loss_unit', models.CharField(choices=[('T', 't'), ('K', 'Kg')], default='T', max_length=2)),
                ('payment_unit', models.CharField(choices=[('T', 't'), ('K', 'Kg')], default='T', max_length=2)),
                ('is_split', models.BooleanField(default=False)),
                ('is_pump', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderProduct')),
                ('unloading_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.UnLoadingStation')),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unloading_stations',
            field=models.ManyToManyField(through='order.OrderProductDeliver', to='info.UnLoadingStation'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderProduct', to='info.Product'),
        ),
    ]
