# Generated by Django 2.2.1 on 2019-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderloadingstation',
            name='is_same_station',
            field=models.BooleanField(default=False),
        ),
    ]
