# Generated by Django 2.2.1 on 2019-10-28 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('D', '司机'), ('E', '押运员')], default='D', max_length=1)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('job', '-assigned_on'),
            },
        ),
        migrations.RemoveField(
            model_name='jobescort',
            name='escort',
        ),
        migrations.RemoveField(
            model_name='jobescort',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='associated_drivers',
        ),
        migrations.RemoveField(
            model_name='job',
            name='associated_escorts',
        ),
        migrations.DeleteModel(
            name='JobDriver',
        ),
        migrations.DeleteModel(
            name='JobEscort',
        ),
        migrations.AddField(
            model_name='jobworker',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Job'),
        ),
        migrations.AddField(
            model_name='jobworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='associated_workers',
            field=models.ManyToManyField(related_name='associated_jobs', through='order.JobWorker', to=settings.AUTH_USER_MODEL),
        ),
    ]
