# Generated by Django 2.2.1 on 2019-07-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductdeliver',
            name='job',
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='orderproductdeliver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_delivers', to='order.OrderProductDeliver'),
            preserve_default=False,
        ),
    ]
