# Generated by Django 2.2.1 on 2019-07-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbill',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobbill',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobbill',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
