# Generated by Django 2.2.1 on 2019-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '待更新'), (1, '待对账'), (2, '待开票'), (3, '待结算'), (4, '结算')], default=0),
        ),
    ]
