# Generated by Django 2.2.1 on 2019-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('I', '内部'), ('C', 'App')], default='I', max_length=1),
        ),
    ]
