# Generated by Django 2.2.1 on 2019-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreport',
            name='empty_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='heavy_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='highway_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='normalway_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='total_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
