# Generated by Django 2.2.1 on 2019-07-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
