# Generated by Django 2.2.1 on 2019-08-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('orders', models.PositiveIntegerField(default=0)),
                ('weights', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='hr.CustomerProfile')),
            ],
            options={
                'ordering': ('month',),
            },
        ),
    ]
