# Generated by Django 2.2.1 on 2019-07-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190715_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='loading_weight',
        ),
    ]
