# Generated by Django 2.2.1 on 2019-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191007_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='arranged_weight',
            field=models.FloatField(default=0),
        ),
    ]
