# Generated by Django 2.2.1 on 2019-07-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190717_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstationproduct',
            name='orderproductdeliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_delivers', to='order.OrderProductDeliver'),
        ),
    ]
