# Generated by Django 2.2.1 on 2019-08-01 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190729_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleuserbind',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleuserbind',
            name='escort',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_as_escort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleuserbind',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bind', to='vehicle.Vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleuserbind',
            unique_together=set(),
        ),
    ]
