# Generated by Django 2.2.1 on 2019-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreport',
            options={'ordering': ('-month',)},
        ),
    ]
