# Generated by Django 2.2.1 on 2019-11-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191111_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobworker',
            options={'ordering': ('job', '-last_active', '-assigned_on')},
        ),
        migrations.RenameField(
            model_name='jobworker',
            old_name='active',
            new_name='last_active',
        ),
    ]
