# Generated by Django 2.2.1 on 2019-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderloadingstation_is_same_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='total_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='loading_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='unloading_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproductdeliver',
            name='weight',
            field=models.FloatField(),
        ),
    ]
