# Generated by Django 2.2.1 on 2019-10-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191028_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='total_weight',
        ),
    ]
