# Generated by Django 2.2.1 on 2019-10-05 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_job_is_same_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstation',
            name='route',
        ),
        migrations.AddField(
            model_name='job',
            name='routes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
