# Generated by Django 2.2.1 on 2019-06-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190606_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated']},
        ),
    ]
