# Generated by Django 2.2.1 on 2019-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190623_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', '未开始'), ('I', '已开始'), ('C', '已完成')], default='P', max_length=1),
        ),
    ]
