# Generated by Django 2.2.1 on 2019-07-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190726_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproductdeliver',
            name='arriving_due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
