# Generated by Django 2.2.1 on 2019-07-20 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190720_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobbill',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
