# Generated by Django 2.2.1 on 2019-05-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderloadingstation_quality_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderloadingstation',
            old_name='time',
            new_name='due_time',
        ),
    ]
