# Generated by Django 2.2.1 on 2019-10-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191005_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loading_due_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 11, 20, 53, 243678)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobstation',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
