# Generated by Django 2.2.1 on 2019-08-01 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190801_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleuserbind',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='vehicleuserbind',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleuserbind',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
