# Generated by Django 2.2.1 on 2019-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190829_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobreport',
            options={'ordering': ('-month',)},
        ),
    ]
