# Generated by Django 2.2.1 on 2019-10-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderproduct_arranged_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-finished_on',)},
        ),
    ]
