# Generated by Django 2.2.1 on 2019-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190726_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrangement_status',
            field=models.CharField(choices=[('P', '未派车'), ('I', '派车中'), ('C', '派车完')], default='P', max_length=1),
        ),
    ]
