# Generated by Django 2.2.1 on 2019-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191005_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loading_due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
