# Generated by Django 2.2.1 on 2019-10-09 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191007_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdriver',
            options={'ordering': ('job', '-assigned_on')},
        ),
        migrations.AlterModelOptions(
            name='jobescort',
            options={'ordering': ('job', '-assigned_on')},
        ),
        migrations.RenameField(
            model_name='jobdriver',
            old_name='finished_at',
            new_name='finished_on',
        ),
        migrations.RenameField(
            model_name='jobdriver',
            old_name='started_at',
            new_name='started_on',
        ),
        migrations.RenameField(
            model_name='jobescort',
            old_name='finished_at',
            new_name='finished_on',
        ),
        migrations.RenameField(
            model_name='jobescort',
            old_name='started_at',
            new_name='started_on',
        ),
        migrations.AddField(
            model_name='jobdriver',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobescort',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
