# Generated by Django 2.2.1 on 2019-08-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190801_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finish_due_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loading_station',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quality_station',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_due_time',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='loss_unit',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price_weight_measure_unit',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='unloading_stations',
        ),
    ]
