# Generated by Django 2.2.1 on 2019-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191111_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworker',
            name='start_due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworker',
            name='start_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
