# Generated by Django 2.2.1 on 2019-11-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191112_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobworker',
            options={'ordering': ('job', '-is_active', '-assigned_on')},
        ),
        migrations.RenameField(
            model_name='jobworker',
            old_name='last_active',
            new_name='is_active',
        ),
    ]
