# Generated by Django 2.2.1 on 2019-10-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191005_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdriver',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AlterModelOptions(
            name='jobescort',
            options={'ordering': ('-started_at',)},
        ),
        migrations.RenameField(
            model_name='jobdriver',
            old_name='finish_at',
            new_name='finished_at',
        ),
        migrations.RenameField(
            model_name='jobdriver',
            old_name='start_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='jobescort',
            old_name='finish_at',
            new_name='finished_at',
        ),
        migrations.RenameField(
            model_name='jobescort',
            old_name='start_at',
            new_name='started_at',
        ),
    ]
