# Generated by Django 2.2.1 on 2019-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190805_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_same_station',
            new_name='invoice_ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.FloatField(default=0),
        ),
    ]
