# Generated by Django 2.2.1 on 2019-10-11 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191009_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingstationproductcheck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
