# Generated by Django 2.2.1 on 2019-08-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190806_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='total_weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='total_weight_measure_unit',
            new_name='weight_measure_unit',
        ),
    ]
