# Generated by Django 2.2.1 on 2019-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_loadingstationproductcheck_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstationproduct',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
