# Generated by Django 2.2.1 on 2019-10-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191006_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='associated_drivers',
            field=models.ManyToManyField(related_name='associated_drivers', through='order.JobDriver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='associated_escorts',
            field=models.ManyToManyField(related_name='associated_escorts', through='order.JobEscort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobescort',
            name='escort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_escorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
