# Generated by Django 2.2.1 on 2019-10-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_jobstationproduct_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstation',
            name='transport_unit_price',
            field=models.FloatField(default=0),
        ),
    ]
