# Generated by Django 2.2.1 on 2019-08-06 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190806_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstationproduct',
            old_name='branches',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='job',
            name='finish_due_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_due_time',
        ),
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='orderproductdeliver',
        ),
        migrations.AddField(
            model_name='job',
            name='is_same_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 17, 20, 37, 177294, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
