# Generated by Django 2.2.1 on 2019-10-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191006_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleUserBind',
        ),
    ]
