# Generated by Django 2.2.1 on 2019-10-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='loading_station',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='transport_unit_price',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='unloading_station',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='job_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.JobStation'),
            preserve_default=False,
        ),
    ]
