# Generated by Django 2.2.1 on 2020-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='additive',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='density',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='volume',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
