# Generated by Django 2.2.1 on 2019-08-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190807_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstationproduct',
            old_name='branch',
            new_name='branches',
        ),
    ]
