# Generated by Django 2.2.1 on 2019-08-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190807_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivered_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
