# Generated by Django 2.2.1 on 2020-04-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200318_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rest_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_rest_place', to='info.Station'),
        ),
    ]
