# Generated by Django 2.2.1 on 2020-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200427_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
