# Generated by Django 2.2.1 on 2019-08-07 18:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190807_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='mission_weight',
        ),
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='weight',
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='mission_branches',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobstationproduct',
            name='branches',
            field=jsonfield.fields.JSONField(),
        ),
    ]
