# Generated by Django 2.2.1 on 2019-08-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190808_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='mission_branches',
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='branch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='mission_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
