# Generated by Django 2.2.1 on 2019-08-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190808_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.PositiveIntegerField(default=0)),
                ('density', models.FloatField(default=0)),
                ('additive', models.FloatField(default=0)),
                ('man_hole', models.CharField(max_length=100)),
                ('branch_hole', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Job')),
            ],
        ),
    ]
