# Generated by Django 2.2.1 on 2019-08-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190809_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='is_pump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
    ]
