# Generated by Django 2.2.1 on 2019-08-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20190821_0612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProductDeliver',
        ),
    ]
