# Generated by Django 2.2.1 on 2019-08-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_delete_orderproductdeliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbill',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '吃饭'), (1, '停车'), (2, '洗车'), (3, '住宿')], default=4),
        ),
    ]
