# Generated by Django 2.2.1 on 2019-08-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190821_1328'),
        ('order', '0018_auto_20190822_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStationProductDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingStationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingStationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='jobstationproduct',
            old_name='weight',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='jobstationproduct',
            name='document',
        ),
        migrations.RemoveField(
            model_name='qualitycheck',
            name='branch_hole',
        ),
        migrations.RemoveField(
            model_name='qualitycheck',
            name='man_hole',
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='branch_hole',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobstationproduct',
            name='man_hole',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobBill',
        ),
        migrations.AddField(
            model_name='loadingstationproduct',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Job'),
        ),
        migrations.AddField(
            model_name='loadingstationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Product'),
        ),
        migrations.AddField(
            model_name='loadingstationdocument',
            name='loading_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.LoadingStationProduct'),
        ),
        migrations.AddField(
            model_name='jobstationproductdocument',
            name='job_station_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.JobStationProduct'),
        ),
    ]
