# Generated by Django 2.2.1 on 2019-08-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20190823_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingstationdocument',
            name='loading_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.LoadingStationProductCheck'),
        ),
    ]
