# Generated by Django 2.2.1 on 2019-08-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20190823_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingstationproductcheck',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Job'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Job'),
        ),
    ]
