# Generated by Django 2.2.1 on 2019-08-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20190823_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingstationproductcheck',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_checks', to='order.Job'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='order.Job'),
        ),
    ]
