# Generated by Django 2.2.1 on 2019-08-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20190823_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstationproduct',
            options={'ordering': ['job_station', 'branch']},
        ),
    ]
