# Generated by Django 2.2.1 on 2019-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191120_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransaction',
            name='amount_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outtransaction',
            name='amount_unit',
            field=models.CharField(max_length=100),
        ),
    ]
