# Generated by Django 2.2.1 on 2019-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20191120_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='outtransaction',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='outtransaction',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outtransaction',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='outtransaction',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
