# Generated by Django 2.2.1 on 2019-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='selfdrivingpaymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='selfdrivingpaymentrequest',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
