# Generated by Django 2.2.1 on 2019-10-09 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('info', '0002_othercosttype_tickettype'),
        ('vehicle', '0004_auto_20191008_1224'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrequest',
            name='request_type',
            field=models.PositiveIntegerField(choices=[(0, '假期'), (1, '车辆修理'), (2, '自驾车补贴'), (3, '费用报销')], default=0),
        ),
        migrations.CreateModel(
            name='SelfDrivingPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('mileage', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_driving_requests', to='hr.Department')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_driving_request', to='business.BasicRequest')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateTimeField()),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department')),
                ('other_cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.OtherCostType')),
                ('plate_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.Vehicle')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TicketType')),
            ],
        ),
    ]
