# Generated by Django 2.2.1 on 2019-08-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rest_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RestRequestApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(auto_now_add=True)),
                ('step', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rest_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.RestRequest')),
            ],
        ),
        migrations.AddField(
            model_name='restrequest',
            name='approvers',
            field=models.ManyToManyField(through='business.RestRequestApprove', to=settings.AUTH_USER_MODEL),
        ),
    ]
