# Generated by Django 2.2.1 on 2019-10-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaymentrequest',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment_request', to='business.BasicRequest'),
            preserve_default=False,
        ),
    ]
