# Generated by Django 2.2.1 on 2019-10-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20191009_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepaymentrequest',
            old_name='plate_num',
            new_name='vehicle',
        ),
    ]
