# Generated by Django 2.2.1 on 2019-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_restrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverchangerequest',
            name='change_place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escortchangerequest',
            name='change_place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingrequest',
            name='place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
