# Generated by Django 2.2.1 on 2019-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190903_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrequest',
            name='cancelled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
