# Generated by Django 2.2.1 on 2019-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190819_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequestapprove',
            name='approved_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
