# Generated by Django 2.2.1 on 2019-10-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20191009_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepaymentrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='selfdrivingpaymentrequest',
            name='reason',
        ),
    ]
