# Generated by Django 2.2.1 on 2019-08-19 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_auto_20190819_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrequest',
            name='cc',
            field=models.ManyToManyField(related_name='requests_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
