# Generated by Django 2.2.1 on 2019-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190703_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverchangerequest',
            name='change_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escortchangerequest',
            name='change_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
