# Generated by Django 2.2.1 on 2019-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20191009_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymentrequest',
            name='paid_on',
            field=models.DateField(),
        ),
    ]
