# Generated by Django 2.2.1 on 2019-07-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0005_auto_20190703_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverchangerequest',
            name='old_driver',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='driver_change_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escortchangerequest',
            name='old_escort',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='escort_change_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverchangerequest',
            name='new_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_change_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escortchangerequest',
            name='new_escort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escort_change_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
