# Generated by Django 2.2.1 on 2019-08-19 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0005_restrequest_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRequestApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_type', models.CharField(choices=[('P', '职位'), ('W', '人员')], default='W', max_length=1)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestRequestCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_type', models.CharField(choices=[('P', '职位'), ('W', '人员')], default='W', max_length=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='cc',
        ),
        migrations.AlterField(
            model_name='restrequest',
            name='approvers',
            field=models.ManyToManyField(related_name='rest_request_as_approver', through='business.RestRequestApprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RestRequestApprove',
        ),
        migrations.AddField(
            model_name='restrequestcc',
            name='rest_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.RestRequest'),
        ),
        migrations.AddField(
            model_name='restrequestapprover',
            name='rest_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.RestRequest'),
        ),
        migrations.AddField(
            model_name='restrequest',
            name='ccs',
            field=models.ManyToManyField(through='business.RestRequestCC', to=settings.AUTH_USER_MODEL),
        ),
    ]
