# Generated by Django 2.2.1 on 2019-07-03 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('business', '0006_auto_20190703_0710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverchangerequest',
            unique_together={('job', 'old_driver', 'new_driver')},
        ),
        migrations.AlterUniqueTogether(
            name='escortchangerequest',
            unique_together={('job', 'old_escort', 'new_escort')},
        ),
    ]
