# Generated by Django 2.2.1 on 2019-08-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20190820_0126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restrequest',
            unique_together=set(),
        ),
    ]
