# Generated by Django 2.2.1 on 2019-08-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0008_auto_20190820_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRepairRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('I', '查看刹车')], default='B', max_length=1)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vehicle_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['approved', '-approved_time', '-request_time'],
            },
        ),
    ]
