# Generated by Django 2.2.1 on 2019-08-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_vehicledriverdailybind_get_off'),
        ('business', '0009_vehiclerepairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepairrequest',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
            preserve_default=False,
        ),
    ]
