# Generated by Django 2.2.1 on 2019-08-21 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_vehiclerepairrequest_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['approved', '-approved_time', '-request_time'],
            },
        ),
        migrations.CreateModel(
            name='RequestApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_type', models.CharField(choices=[('P', '职位'), ('W', '人员')], default='W', max_length=1)),
                ('approved', models.BooleanField(default=False)),
                ('approved_time', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BasicRequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_type', models.CharField(choices=[('P', '职位'), ('W', '人员')], default='W', max_length=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BasicRequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='escortchangerequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='escortchangerequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='escortchangerequest',
            name='new_escort',
        ),
        migrations.RemoveField(
            model_name='escortchangerequest',
            name='old_escort',
        ),
        migrations.RemoveField(
            model_name='parkingrequest',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='parkingrequest',
            name='escort',
        ),
        migrations.RemoveField(
            model_name='parkingrequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='parkingrequest',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='restrequestapprover',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='restrequestapprover',
            name='rest_request',
        ),
        migrations.RemoveField(
            model_name='restrequestcc',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='restrequestcc',
            name='rest_request',
        ),
        migrations.AlterModelOptions(
            name='restrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiclerepairrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='approved_time',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='ccs',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='request_time',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='approved_time',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='request_time',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='vehiclerepairrequest',
            name='to_date',
        ),
        migrations.DeleteModel(
            name='DriverChangeRequest',
        ),
        migrations.DeleteModel(
            name='EscortChangeRequest',
        ),
        migrations.DeleteModel(
            name='ParkingRequest',
        ),
        migrations.DeleteModel(
            name='RestRequestApprover',
        ),
        migrations.DeleteModel(
            name='RestRequestCC',
        ),
        migrations.AddField(
            model_name='basicrequest',
            name='approvers',
            field=models.ManyToManyField(related_name='request_as_approver', through='business.RequestApprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicrequest',
            name='ccs',
            field=models.ManyToManyField(related_name='request_as_cc', through='business.RequestCC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restrequest',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.BasicRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclerepairrequest',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.BasicRequest'),
            preserve_default=False,
        ),
    ]
