# Generated by Django 2.2.1 on 2019-08-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20190822_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrequest',
            name='request_type',
            field=models.CharField(choices=[('R', 'Rest Request'), ('V', 'Vehicle Repair')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='restrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rest_request', to='business.BasicRequest'),
        ),
        migrations.AlterField(
            model_name='vehiclerepairrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_repair_request', to='business.BasicRequest'),
        ),
    ]
