# Generated by Django 2.2.1 on 2019-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_requestdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrequest',
            name='request_type',
            field=models.CharField(choices=[('R', '假期'), ('V', '车辆修理')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehiclerepairrequest',
            name='category',
            field=models.CharField(choices=[('B', '查看刹车')], default='B', max_length=1),
        ),
    ]
