# Generated by Django 2.2.1 on 2019-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
