# Generated by Django 2.2.1 on 2019-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='policy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
