# Generated by Django 2.2.1 on 2019-06-29 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='policy',
            field=models.PositiveIntegerField(choices=[(0, '最快捷模式'), (1, '最经济模式'), (2, '最短距离模式')], default=0),
        ),
    ]
