# Generated by Django 2.2.1 on 2019-05-24 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_path'),
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=18)),
                ('policy', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
