# Generated by Django 2.2.1 on 2019-06-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_auto_20190629_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('-updated',)},
        ),
    ]
