# Generated by Django 2.2.1 on 2019-10-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20191001_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='from_time',
            new_name='finish_time',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='to_time',
            new_name='start_time',
        ),
    ]
