# Generated by Django 2.2.1 on 2019-06-14 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('T', '牵引车'), ('S', '半挂罐车')], default='T', max_length=1)),
                ('plate_num', models.CharField(max_length=100, unique=True)),
                ('identifier_code', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('T', '通华'), ('L', '解放'), ('Y', '扬州中集')], default='T', max_length=1)),
                ('use_for', models.CharField(blank=True, max_length=100, null=True)),
                ('total_load', models.DecimalField(decimal_places=1, max_digits=5)),
                ('actual_load', models.DecimalField(decimal_places=1, max_digits=5)),
                ('affiliation_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('use_started_on', models.DateField(blank=True, null=True)),
                ('use_expires_on', models.DateField(blank=True, null=True)),
                ('service_area', models.CharField(max_length=100)),
                ('obtain_method', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_registered_on', models.DateField(blank=True, null=True)),
                ('cert_active_on', models.DateField(blank=True, null=True)),
                ('cert_expires_on', models.DateField(blank=True, null=True)),
                ('insurance_active_on', models.DateField(blank=True, null=True)),
                ('insurance_expires_on', models.DateField(blank=True, null=True)),
                ('branches', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('engine_model', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_power', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission_model', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_displacement', models.CharField(blank=True, max_length=100, null=True)),
                ('tire_rules', models.CharField(blank=True, max_length=100, null=True)),
                ('tank_material', models.CharField(blank=True, max_length=100, null=True)),
                ('is_gps_installed', models.BooleanField(default=False)),
                ('is_gps_working', models.BooleanField(default=False)),
                ('with_pump', models.BooleanField(default=False)),
                ('main_car_size', models.CharField(blank=True, max_length=100, null=True)),
                ('main_car_color', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer_car_size', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer_car_color', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'In Work'), ('R', 'Repair')], default='A', max_length=1)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
