# Generated by Django 2.2.1 on 2019-06-07 08:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(choices=[('T', '牵引车'), ('S', '半挂罐车')], default='T', max_length=1)),
                ('plate_num', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('T', '通华'), ('L', '解放'), ('Y', '扬州中集')], default='T', max_length=1)),
                ('load', models.DecimalField(decimal_places=1, max_digits=5)),
                ('branches', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('status', models.CharField(choices=[('A', 'Available'), ('P', 'In Work'), ('R', 'Repair')], default='A', max_length=1)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(choices=[('1', 'D1'), ('2', 'D2')], default='1', max_length=1)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
