# Generated by Django 2.2.1 on 2019-06-05 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[1], size=None),
            preserve_default=False,
        ),
    ]
