# Generated by Django 2.2.1 on 2019-10-06 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDriverEscortBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_as_driver', to=settings.AUTH_USER_MODEL)),
                ('escort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_as_escort', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bind', to='vehicle.Vehicle')),
            ],
        ),
    ]
