# Generated by Django 2.2.1 on 2019-07-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleUserBind',
        ),
    ]
