# Generated by Django 2.2.1 on 2019-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='service_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
