# Generated by Django 2.2.1 on 2019-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('T', '通华'), ('L', '解放'), ('Y', '扬州中集')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(choices=[('T', '牵引车'), ('S', '半挂罐车')], default='T', max_length=1),
        ),
    ]
