# Generated by Django 2.2.1 on 2019-10-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_active_on',
            new_name='license_active_on',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_active_on_2',
            new_name='license_active_on_2',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_authority',
            new_name='license_authority',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_authority_2',
            new_name='license_authority_2',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_expires_on',
            new_name='license_expires_on',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_expires_on_2',
            new_name='license_expires_on_2',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_id',
            new_name='license_id',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_id_2',
            new_name='license_id_2',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_registered_on',
            new_name='license_registered_on',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_registered_on_2',
            new_name='license_registered_on_2',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_type',
            new_name='license_type',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cert_type_2',
            new_name='license_type_2',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operation_permit_active_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operation_permit_active_on_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operation_permit_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operation_permit_expires_on_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
