# Generated by Django 2.2.1 on 2019-06-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='speed',
        ),
    ]
