# Generated by Django 2.2.1 on 2019-08-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledriverdailybind',
            options={'ordering': ['-get_on', 'vehicle']},
        ),
    ]
