# Generated by Django 2.2.1 on 2019-06-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='actual_load',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
