# Generated by Django 2.2.1 on 2019-11-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_company_vehicle',
            field=models.BooleanField(default=True),
        ),
    ]
