# Generated by Django 2.2.1 on 2019-10-30 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20191023_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tank_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
