# Generated by Django 2.2.1 on 2019-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_is_company_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletire',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
