# Generated by Django 2.2.1 on 2019-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehiclemaintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenancerequest',
            name='category',
            field=models.CharField(choices=[('R', 'Repair')], max_length=1),
        ),
    ]
