# Generated by Django 2.2.1 on 2019-10-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicledriverdailybind_get_off_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireTreadDepthCheckHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tread_depth', models.FloatField(default=0)),
                ('checked_on', models.DateTimeField()),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicle.TireManagementHistory')),
            ],
            options={
                'ordering': ('-checked_on',),
            },
        ),
    ]
