# Generated by Django 2.2.1 on 2019-10-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20191015_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[(0, 'Available'), (1, 'Under wheel'), (2, 'Repair')], default=0, max_length=1),
        ),
    ]
