# Generated by Django 2.2.1 on 2019-08-08 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_vehiclecheckitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBeforeDrivingCheckHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBeforeDrivingItemCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCheckItem')),
                ('vehicle_check_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleBeforeDrivingCheckHistory')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='check_items',
            field=models.ManyToManyField(through='vehicle.VehicleBeforeDrivingItemCheck', to='vehicle.VehicleCheckItem'),
        ),
        migrations.AddField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
    ]
