# Generated by Django 2.2.1 on 2019-06-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20190621_0837'),
        ('vehicle', '0002_auto_20190621_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenancerequest',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.StaffProfile'),
            preserve_default=False,
        ),
    ]
