# Generated by Django 2.2.1 on 2019-06-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190617_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemaintenancerequest',
            old_name='maintenace_from',
            new_name='maintenance_from',
        ),
        migrations.RenameField(
            model_name='vehiclemaintenancerequest',
            old_name='maintenace_to',
            new_name='maintenance_to',
        ),
    ]
