# Generated by Django 2.2.1 on 2019-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190624_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleuserbind',
            name='bind_method',
            field=models.CharField(choices=[('A', 'By Admin'), ('J', 'By Job')], default='A', max_length=1),
        ),
    ]
