# Generated by Django 2.2.1 on 2019-08-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('vehicle', '0003_auto_20190831_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='accessories_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='mileage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Station'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancehistory',
            name='work_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenancehistory',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '驱动轮'), (1, '齿轮油')], default=0),
        ),
    ]
