# Generated by Django 2.2.1 on 2019-06-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehiclemaintenancerequest_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemaintenancerequest',
            old_name='request',
            new_name='requester',
        ),
    ]
