# Generated by Django 2.2.1 on 2019-06-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190606_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['updated']},
        ),
    ]
