# Generated by Django 2.2.1 on 2019-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20191118_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiretreaddepthcheckhistory',
            name='mileage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tiretreaddepthcheckhistory',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tiretreaddepthcheckhistory',
            name='symptom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
