# Generated by Django 2.2.1 on 2019-05-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190525_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
