# Generated by Django 2.2.1 on 2019-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190809_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleafterdrivingcheckhistory',
            name='checked_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='checked_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicledrivingcheckhistory',
            name='checked_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
