# Generated by Django 2.2.1 on 2019-11-05 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191023_2224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0004_auto_20191101_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleWorkerBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('D', '司机'), ('E', '押运员')], default='D', max_length=1)),
                ('get_on', models.DateTimeField(auto_now_add=True)),
                ('get_off', models.DateTimeField(blank=True, null=True)),
                ('get_off_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vehicle_bind', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-get_on', 'vehicle'],
            },
        ),
        migrations.DeleteModel(
            name='VehicleDriverDailyBind',
        ),
    ]
