# Generated by Django 2.2.1 on 2019-06-24 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0004_vehicleuserbind_bind_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleuserbind',
            old_name='user',
            new_name='driver',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleuserbind',
            unique_together={('vehicle', 'driver')},
        ),
    ]
