# Generated by Django 2.2.1 on 2019-06-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190617_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclemaintenancerequest',
            unique_together={('vehicle', 'approved')},
        ),
    ]
