# Generated by Django 2.2.1 on 2019-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20191120_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiretreaddepthcheckhistory',
            name='checked_on',
            field=models.DateTimeField(),
        ),
    ]
