# Generated by Django 2.2.1 on 2019-08-31 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190831_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
