# Generated by Django 2.2.1 on 2019-06-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190606_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-updated']},
        ),
    ]
