# Generated by Django 2.2.1 on 2019-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20191120_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='after_driving_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='before_driving_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='driving_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
