# Generated by Django 2.2.1 on 2019-06-24 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0005_auto_20190624_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleuserbind',
            unique_together={('vehicle', 'driver', 'escort')},
        ),
    ]
