# Generated by Django 2.2.1 on 2019-08-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190809_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='actual_load2',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand2',
            field=models.CharField(choices=[('T', '通华'), ('L', '解放'), ('Y', '扬州中集')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_active_on2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_authority2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_expires_on2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_id2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_registered_on2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cert_type2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='identifier_code2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_active_on2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expires_on2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model2',
            field=models.CharField(choices=[('T', '牵引车'), ('S', '半挂罐车')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_num2',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_load2',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='use_for2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
