# Generated by Django 2.2.1 on 2019-11-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20191105_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Available'), (1, 'Driver on'), (2, 'Escort on'), (3, 'Under wheel'), (4, 'Repair')], default=0),
        ),
    ]
