# Generated by Django 2.2.1 on 2019-08-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190831_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TireManagementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('installed_on', models.DateTimeField()),
                ('previous_mileage', models.PositiveIntegerField(default=0)),
                ('mileage_limit', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tire_type', models.CharField(max_length=100)),
                ('tread_depth', models.FloatField(default=0)),
                ('manufacturer', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('vehicle_tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicle.VehicleTire')),
            ],
            options={
                'ordering': ['-installed_on'],
            },
        ),
    ]
