# Generated by Django 2.2.1 on 2019-11-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20191120_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecheckhistory',
            options={'ordering': ['-updated']},
        ),
    ]
