# Generated by Django 2.2.1 on 2019-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_tiremanagementhistory_vehicletire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiremanagementhistory',
            old_name='previous_mileage',
            new_name='mileage',
        ),
        migrations.AlterField(
            model_name='tiremanagementhistory',
            name='installed_on',
            field=models.DateField(),
        ),
    ]
