# Generated by Django 2.2.1 on 2019-08-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0007_auto_20190815_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='problems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VehicleDriverDailyBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_on', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'get_on'],
            },
        ),
    ]
