# Generated by Django 2.2.1 on 2019-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20190902_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiremanagementhistory',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
