# Generated by Django 2.2.1 on 2019-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20191120_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_company_vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='department',
            field=models.PositiveIntegerField(choices=[(0, '油品部门'), (1, '壳牌'), (2, '外协车辆')], default=0),
        ),
    ]
