# Generated by Django 2.2.1 on 2019-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20191121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenancehistory',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '车辆保养'), (1, '换季保养'), (2, '主车保轮'), (3, '挂车保轮'), (4, '车辆电器路维修'), (5, '轮胎维修'), (6, '轮胎更换'), (7, '附属设备维修'), (8, '中集设备维修'), (9, '车辆救援费用'), (0, '车辆物品配备车辆保养'), (10, '换季保养'), (11, '主车保轮'), (12, '挂车保轮'), (13, '车辆电器路维修'), (14, '轮胎维修'), (15, '轮胎更换'), (16, '附属设备维修'), (17, '中集设备维修'), (18, '车辆救援费用'), (19, '车辆物品配备')], default=0),
        ),
    ]
