# Generated by Django 2.2.1 on 2019-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20190902_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiremanagementhistory',
            name='installed_on',
            field=models.DateTimeField(),
        ),
    ]
