# Generated by Django 2.2.1 on 2019-08-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20190818_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDrivingDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('vehicle_check_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleDrivingCheckHistory')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBeforeDrivingDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('vehicle_check_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleBeforeDrivingCheckHistory')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAfterDrivingDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('vehicle_check_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleAfterDrivingCheckHistory')),
            ],
        ),
    ]
