# Generated by Django 2.2.1 on 2019-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20190902_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiremanagementhistory',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiremanagementhistory',
            name='mileage_limit',
            field=models.FloatField(default=0),
        ),
    ]
