# Generated by Django 2.2.1 on 2019-08-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20190818_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleafterdrivingdocument',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.VehicleAfterDrivingCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehiclebeforedrivingdocument',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.VehicleBeforeDrivingCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehicledrivingdocument',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.VehicleDrivingCheckHistory'),
        ),
    ]
