# Generated by Django 2.2.1 on 2020-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20191127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Available'), (1, 'Driver on'), (2, 'Escort on'), (3, '驾驶中'), (4, '修理中')], default=0),
        ),
    ]
