# Generated by Django 2.2.1 on 2019-08-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20190819_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledrivingcheckhistory',
            options={'ordering': ['-checked_time']},
        ),
    ]
