# Generated by Django 2.2.1 on 2019-08-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20190819_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleafterdrivingcheckhistory',
            options={'ordering': ['-checked_time']},
        ),
        migrations.AlterModelOptions(
            name='vehiclebeforedrivingcheckhistory',
            options={'ordering': ['-checked_time']},
        ),
    ]
