# Generated by Django 2.2.1 on 2019-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20190819_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriverdailybind',
            name='get_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
