# Generated by Django 2.2.1 on 2019-08-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0015_vehicledriverdailybind_get_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCheckDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('B', '行车前'), ('D', '行车中'), ('A', '行车后')], default='B', max_length=1)),
                ('document', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCheckHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('before_driving_checked_time', models.DateTimeField(blank=True, null=True)),
                ('driving_checked_time', models.DateTimeField(blank=True, null=True)),
                ('after_driving_checked_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-before_driving_checked_time'],
            },
        ),
        migrations.RemoveField(
            model_name='vehicleafterdrivingdocument',
            name='vehicle_check_history',
        ),
        migrations.RemoveField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='check_items',
        ),
        migrations.RemoveField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehiclebeforedrivingcheckhistory',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehiclebeforedrivingdocument',
            name='vehicle_check_history',
        ),
        migrations.RemoveField(
            model_name='vehicledrivingcheckhistory',
            name='check_items',
        ),
        migrations.RemoveField(
            model_name='vehicledrivingcheckhistory',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicledrivingcheckhistory',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicledrivingdocument',
            name='vehicle_check_history',
        ),
        migrations.AlterField(
            model_name='vehicleafterdrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_driving_items', to='vehicle.VehicleCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehiclebeforedrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_driving_items', to='vehicle.VehicleCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehicledrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_items', to='vehicle.VehicleCheckHistory'),
        ),
        migrations.DeleteModel(
            name='VehicleAfterDrivingCheckHistory',
        ),
        migrations.DeleteModel(
            name='VehicleAfterDrivingDocument',
        ),
        migrations.DeleteModel(
            name='VehicleBeforeDrivingCheckHistory',
        ),
        migrations.DeleteModel(
            name='VehicleBeforeDrivingDocument',
        ),
        migrations.DeleteModel(
            name='VehicleDrivingCheckHistory',
        ),
        migrations.DeleteModel(
            name='VehicleDrivingDocument',
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='after_driving_checked_items',
            field=models.ManyToManyField(related_name='afters', through='vehicle.VehicleAfterDrivingItemCheck', to='vehicle.VehicleCheckItem'),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='before_driving_checked_items',
            field=models.ManyToManyField(related_name='befores', through='vehicle.VehicleBeforeDrivingItemCheck', to='vehicle.VehicleCheckItem'),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='driving_checked_items',
            field=models.ManyToManyField(related_name='drivings', through='vehicle.VehicleDrivingItemCheck', to='vehicle.VehicleCheckItem'),
        ),
        migrations.AddField(
            model_name='vehiclecheckhistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclecheckdocument',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.VehicleCheckHistory'),
        ),
    ]
