# Generated by Django 2.2.1 on 2019-08-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_auto_20190821_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleafterdrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehiclebeforedrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCheckHistory'),
        ),
        migrations.AlterField(
            model_name='vehicledrivingitemcheck',
            name='vehicle_check_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCheckHistory'),
        ),
    ]
