# Generated by Django 2.2.1 on 2019-08-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_auto_20190822_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriverdailybind',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vehicle_bind', to=settings.AUTH_USER_MODEL),
        ),
    ]
