# Generated by Django 2.2.1 on 2019-08-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_auto_20190824_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledriverdailybind',
            options={'ordering': ['vehicle', '-get_on']},
        ),
    ]
