# Generated by Django 2.2.1 on 2019-08-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_auto_20190824_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecheckhistory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vehicle_checks', to=settings.AUTH_USER_MODEL),
        ),
    ]
