# Generated by Django 2.2.1 on 2019-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msg_type',
            field=models.PositiveIntegerField(choices=[(0, 'Job Notification'), (1, 'Enter Area Notification'), (2, 'Exit Area Notification'), (3, 'Black Dot Notification'), (10, 'Rest Request Notification'), (11, 'Vehicle Maintenance Notification'), (12, 'Parking Request Notification'), (13, 'Driver Change Notification'), (14, 'Escort Change Notification'), (15, 'Traffic Accident Notification')], default=0),
        ),
    ]
