# Generated by Django 2.2.1 on 2019-07-16 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
