# Generated by Django 2.2.1 on 2019-07-20 17:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=jsonfield.fields.JSONField(),
        ),
    ]
