# Generated by Django 2.2.1 on 2019-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20191114_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='G7MQTTEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('push_time', models.DateTimeField(blank=True, null=True)),
                ('plate_num', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('end_lng', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
