# Generated by Django 2.2.1 on 2019-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_g7mqttevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g7mqttevent',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, '停留事件'), (1, '怠速事件'), (2, 'EMS事件')], default=0),
        ),
    ]
