# Generated by Django 2.2.1 on 2019-11-14 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_is_company_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0007_auto_20191114_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g7mqttevent',
            name='plate_num',
        ),
        migrations.AddField(
            model_name='g7mqttevent',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='g7mqttevent',
            name='escort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_escort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='g7mqttevent',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
            preserve_default=False,
        ),
    ]
