# Generated by Django 2.2.1 on 2019-06-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_delete_jobbilldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bill', models.ImageField(upload_to='')),
                ('category', models.PositiveIntegerField(choices=[(0, 'Bill from Loading Station'), (1, 'Bill from Quality Station'), (2, 'Bill from UnLoading Station'), (3, 'Bill from Oil Station'), (4, 'Bill from traffic')], default=0)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='job.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
