# Generated by Django 2.2.1 on 2019-08-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etccardchargehistory',
            options={'ordering': ['-charged_on']},
        ),
        migrations.AlterModelOptions(
            name='fuelcardchargehistory',
            options={'ordering': ['-charged_on']},
        ),
    ]
