# Generated by Django 2.2.1 on 2019-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdocument',
            name='detail_category',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
