# Generated by Django 2.2.1 on 2019-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdocument',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '加油'), (1, '路票'), (2, '其他')]),
        ),
    ]
