# Generated by Django 2.2.1 on 2019-10-08 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETCBillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_card', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.ETCCard')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FuelBillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_card', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.FuelCard')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oil_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Station')),
            ],
            options={
                'ordering': ['-paid_on', '-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='fuelcardusagehistory',
            name='card',
        ),
        migrations.RemoveField(
            model_name='fuelcardusagehistory',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='fuelcardusagehistory',
            name='oil_station',
        ),
        migrations.AlterField(
            model_name='etccardusagedocument',
            name='etc_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finance.ETCBillHistory'),
        ),
        migrations.AlterField(
            model_name='fuelcardusagedocument',
            name='fuel_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finance.FuelBillHistory'),
        ),
        migrations.DeleteModel(
            name='ETCCardUsageHistory',
        ),
        migrations.DeleteModel(
            name='FuelCardUsageHistory',
        ),
    ]
