# Generated by Django 2.2.1 on 2019-08-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCardUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('paid_on', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ETCCard')),
            ],
        ),
        migrations.CreateModel(
            name='FuelCardChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.FloatField(default=0)),
                ('charged_amount', models.FloatField(default=0)),
                ('charged_on', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FuelCard')),
            ],
        ),
        migrations.CreateModel(
            name='ETCCardUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('paid_on', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ETCCard')),
            ],
        ),
        migrations.CreateModel(
            name='ETCCardChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.FloatField(default=0)),
                ('charged_amount', models.FloatField(default=0)),
                ('charged_on', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ETCCard')),
            ],
        ),
    ]
