# Generated by Django 2.2.1 on 2019-10-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20191008_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETCCardUsageDocument',
            new_name='ETCBillDocument',
        ),
        migrations.RenameModel(
            old_name='FuelCardUsageDocument',
            new_name='FuelBillDocument',
        ),
        migrations.RenameField(
            model_name='etcbilldocument',
            old_name='etc_usage',
            new_name='etc_bill',
        ),
        migrations.RenameField(
            model_name='fuelbilldocument',
            old_name='fuel_usage',
            new_name='fuel_bill',
        ),
    ]
