# Generated by Django 2.2.1 on 2019-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190625_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdocument',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
