# Generated by Django 2.2.1 on 2019-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190809_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etccard',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
