# Generated by Django 2.2.1 on 2019-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190829_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='etccardchargehistory',
            name='after_amount',
            field=models.FloatField(default=0),
        ),
    ]
