# Generated by Django 2.2.1 on 2019-08-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_etccardchargehistory_after_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etccard',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etccard', to='vehicle.Vehicle'),
        ),
    ]
