# Generated by Django 2.2.1 on 2019-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20190809_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etccardchargehistory',
            name='charged_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
