# Generated by Django 2.2.1 on 2019-08-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20190830_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etccard',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etccard', to='vehicle.Vehicle'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.Vehicle'),
        ),
    ]
