# Generated by Django 2.2.1 on 2019-08-29 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190830_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etccardusagehistory',
            options={'ordering': ['-paid_on', '-created_on']},
        ),
        migrations.AddField(
            model_name='etccardusagehistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etccardusagehistory',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
