# Generated by Django 2.2.1 on 2019-08-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190809_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.Vehicle'),
        ),
    ]
