# Generated by Django 2.2.1 on 2019-08-29 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0007_auto_20190830_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='etccardusagehistory',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ETCCardDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('etc_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finance.ETCCardUsageHistory')),
            ],
        ),
    ]
