# Generated by Django 2.2.1 on 2019-08-21 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_auto_20190809_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(default=0)),
                ('category', models.CharField(choices=[(0, '吃饭'), (1, '停车'), (2, '洗车'), (3, '住宿')], default=0, max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='billdocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='created',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='detail_category',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='billdocument',
            name='user',
        ),
        migrations.AddField(
            model_name='billdocument',
            name='document',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billdocument',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finance.Bill'),
        ),
    ]
