# Generated by Django 2.2.1 on 2019-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20190830_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='etccardusagehistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
