# Generated by Django 2.2.1 on 2019-08-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_etccardusagehistory_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETCCardDocument',
            new_name='ETCCardUsageDocument',
        ),
    ]
