# Generated by Django 2.2.1 on 2019-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20190830_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcardusagehistory',
            name='oil_station',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
