# Generated by Django 2.2.1 on 2019-08-30 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_fuelcardusagehistory_oil_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelcardusagehistory',
            old_name='weight',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='fuelcardusagehistory',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
