# Generated by Django 2.2.1 on 2019-08-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20190830_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etccardchargehistory',
            name='charged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
