# Generated by Django 2.2.1 on 2019-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequest',
            name='category',
            field=models.CharField(choices=[(0, '病假'), (1, '私事')], max_length=1),
        ),
    ]
