# Generated by Django 2.2.1 on 2019-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
