# Generated by Django 2.2.1 on 2019-07-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestRequest',
        ),
    ]
