# Generated by Django 2.2.1 on 2019-06-27 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20190626_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
