# Generated by Django 2.2.1 on 2019-10-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_auto_20191027_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOfficerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.CompanySection')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
