# Generated by Django 2.2.1 on 2019-10-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_companysection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysection',
            old_name='name',
            new_name='text',
        ),
    ]
