# Generated by Django 2.2.1 on 2019-06-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20190621_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequest',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '病假'), (1, '私事')], default=0),
        ),
    ]
