# Generated by Django 2.2.1 on 2019-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_department_position_rolemanagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemanagement',
            options={'ordering': ['department', 'position']},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='rolemanagement',
            unique_together={('department', 'position')},
        ),
    ]
