# Generated by Django 2.2.1 on 2019-06-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190627_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='associated_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharges_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
