# Generated by Django 2.2.1 on 2019-10-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20191016_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='status',
        ),
    ]
