# Generated by Django 2.2.1 on 2019-06-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190621_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrequest',
            options={'ordering': ['approved', '-approved_time', '-request_time']},
        ),
    ]
