# Generated by Django 2.2.1 on 2019-06-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_channel_name'),
        ('hr', '0003_auto_20190618_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrequest',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='restrequest',
            unique_together={('staff', 'from_date', 'to_date')},
        ),
    ]
