# Generated by Django 2.2.1 on 2019-06-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0004_auto_20190621_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='restrequest',
            unique_together={('user', 'from_date', 'to_date')},
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='staff',
        ),
    ]
