# Generated by Django 2.2.1 on 2019-10-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_staffprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Available'), (1, 'Driving'), (2, 'Not Available')], default=0),
        ),
    ]
